//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umehluko.Tools.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PractitionerType
    {
        public PractitionerType()
        {
            this.Tariffs = new HashSet<Tariff>();
        }
    
        public int PractitionerTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PracticeTypeCode { get; set; }
        public decimal MaxTreatmentDays { get; set; }
        public byte IsHospital { get; set; }
        public byte IsDentist { get; set; }
        public byte IsAmbulance { get; set; }
        public byte IsSpecialist { get; set; }
        public byte IsAnaesthetist { get; set; }
        public byte IsActive { get; set; }
        public byte IsGP { get; set; }
        public string NRPLPracticeType { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public string Groupings { get; set; }
        public Nullable<bool> IsRequireMedReport { get; set; }
    
        public virtual ICollection<Tariff> Tariffs { get; set; }
    }
}
