//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umehluko.Tools.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffType
    {
        public TariffType()
        {
            this.Tariffs = new HashSet<Tariff>();
            this.TariffBaseUnitCosts = new HashSet<TariffBaseUnitCost>();
            this.Publications = new HashSet<Publication>();
        }
    
        public int TariffTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte IsBaseType { get; set; }
        public byte IsActive { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public Nullable<System.DateTime> UploadDueDate { get; set; }
        public Nullable<short> NotificationDays { get; set; }
    
        public virtual ICollection<Tariff> Tariffs { get; set; }
        public virtual ICollection<TariffBaseUnitCost> TariffBaseUnitCosts { get; set; }
        public virtual ICollection<Publication> Publications { get; set; }
    }
}
