//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umehluko.Tools.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        public int TariffID { get; set; }
        public string ItemCode { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public int TariffBaseUnitCostID { get; set; }
        public decimal RecommendedUnits { get; set; }
        public int VatCodeID { get; set; }
        public int PractitionerTypeID { get; set; }
        public int TariffTypeID { get; set; }
        public int MedicalItemID { get; set; }
        public int SectionID { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public Nullable<bool> IsCopiedFromNRPL { get; set; }
    
        public virtual MedicalItem MedicalItem { get; set; }
        public virtual PractitionerType PractitionerType { get; set; }
        public virtual TariffBaseUnitCost TariffBaseUnitCost { get; set; }
        public virtual TariffType TariffType { get; set; }
    }
}
