//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umehluko.Tools.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffBaseUnitCost
    {
        public TariffBaseUnitCost()
        {
            this.Tariffs = new HashSet<Tariff>();
        }
    
        public int TariffBaseUnitCostID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PublicationID { get; set; }
        public decimal UnitPrice { get; set; }
        public int UnitTypeID { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public int TariffTypeID { get; set; }
        public string LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public Nullable<int> TariffBaseUnitCostTypeId { get; set; }
        public Nullable<bool> IsCopiedFromNRPL { get; set; }
    
        public virtual ICollection<Tariff> Tariffs { get; set; }
        public virtual TariffType TariffType { get; set; }
        public virtual Publication Publication { get; set; }
        public virtual TariffBaseUnitCostType TariffBaseUnitCostType { get; set; }
    }
}
