//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umehluko.Tools.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UmehlukoEntities1 : DbContext
    {
        public UmehlukoEntities1()
            : base("name=UmehlukoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MedicalItem> MedicalItems { get; set; }
        public virtual DbSet<MedicalItemType> MedicalItemTypes { get; set; }
        public virtual DbSet<PractitionerType> PractitionerTypes { get; set; }
        public virtual DbSet<Tariff> Tariffs { get; set; }
        public virtual DbSet<TariffBaseUnitCost> TariffBaseUnitCosts { get; set; }
        public virtual DbSet<TariffType> TariffTypes { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<TariffBaseUnitCostType> TariffBaseUnitCostTypes { get; set; }
    }
}
